"use client";

/**
 * Texture pipeline for the WebGL stages. The five PNG maps generated by
 * scripts/generate-assets.mjs are loaded once through the asset cache and
 * wrapped as THREE textures with the right colour spaces and filtering.
 */

import * as THREE from "three";
import { ASSET_PATHS, loadAssetBlob } from "@/lib/assets";

export interface HeroTextures {
  base: THREE.Texture;
  depth: THREE.Texture;
  alpha: THREE.Texture;
  roughness: THREE.Texture;
  normal: THREE.Texture;
  dispose: () => void;
}

let texturePromise: Promise<HeroTextures> | null = null;

async function loadTexture(url: string, srgb: boolean): Promise<THREE.Texture> {
  const blob = await loadAssetBlob(url);
  const bitmap = await createImageBitmap(blob);
  const texture = new THREE.Texture(bitmap);
  texture.needsUpdate = true;
  texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  texture.wrapS = THREE.ClampToEdgeWrapping;
  texture.wrapT = THREE.ClampToEdgeWrapping;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.generateMipmaps = true;
  texture.anisotropy = 4;
  return texture;
}

/** Load (once) and cache the full hero texture set. */
export function loadHeroTextures(): Promise<HeroTextures> {
  if (!texturePromise) {
    texturePromise = Promise.all([
      loadTexture(ASSET_PATHS.base, true),
      loadTexture(ASSET_PATHS.depth, false),
      loadTexture(ASSET_PATHS.alpha, false),
      loadTexture(ASSET_PATHS.roughness, false),
      loadTexture(ASSET_PATHS.normal, false),
    ]).then(([base, depth, alpha, roughness, normal]) => ({
      base,
      depth,
      alpha,
      roughness,
      normal,
      dispose: () => {
        for (const texture of [base, depth, alpha, roughness, normal]) texture.dispose();
        texturePromise = null;
      },
    }));
    texturePromise.catch(() => {
      texturePromise = null;
    });
  }
  return texturePromise;
}
